
<nav class="navbar centered-h">

	<ul>
		<li><a href="index.php">Home</a></li>
		<li><a class="clear">Purchasables</a>
			<ul>
				<li><a href="departments.php?shop=chroma">Chroma Skins</a></li>
				<li><a href="departments.php?shop=character">Unlock Characters</a></li>
				<li><a href="departments.php?shop=level	">Unlock Levels</a></li>
			</ul>
		</li>
		<li><a href="recipes.php">Highscores</a>
			<ul>
				<li><a href="highscore.php?level=grassy">Grassy Level</a></li>
				<li><a href="highscore.php?level=tropical">Tropical Level</a></li>
				<li><a href="highscore.php?level=fall">Fall Level</a></li>
				<li><a href="highscore.php?level=icy">Icy Level</a></li>
				<li><a href="highscore.php?level=castle">Castle Level</a></li>
			</ul>
		</li>
		<li><a href="shopcart.php">Shopping Cart</a></li>
		<li><a href="register.php">Register</a></li>
		<li><a class="noborder" href="logout.php">Logout</a></li>
	</ul>
	
</nav>

